// This fixture is the first using Pebble instead of Leveldb.  It was generated by a fixturenet
// running geth 1.14.5 using a "merged from Genesis" configuration, as opposed to the previous
// fixtures for which the Merge occurred at block 1.
package postmerge1

import (
	"github.com/cerc-io/eth-testing/chains"
)

var (
	ChainData, err = chains.GetFixture("postmerge1")
)

func init() {
	if err != nil {
		panic(err)
	}
}
